name: sample-rust-action
description: An example GitHub Action written in Rust
author: Dylan Anthony <dbanty@users.noreply.github.com>
inputs:
  error:
    description: 'The error message to display, if any'
    required: false
    default: ''
outputs:
  error:
    description: 'The description of any error that occurred'
runs:
  using: 'docker'
  image: 'ghcr.io/dbanty/sample-rust-action:v1'
  args:
    - ${{ inputs.error }}
